name: EasyTunnel CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          repository: namecheap/mytunnel-server
          ref: master
          path: server
      - name: Start server
        run: |
          npm ci
          npm run dev &
          npx -y wait-on tcp:127.0.0.1:8087 --log
        working-directory: server
      - run: npm test
